apiVersion: cps1.tech/v1alpha1
kind: CPS1Package
metadata:
  name: python-uv
spec:
  name: python-uv
  label: Python (uv)
  icon: python.svg
  properties:
    - name: version
      label: Version
      tip: Python version
      kind: select
      required: true
      values: ["3.13", "3.12", "3.11", "3.10", "3.9"]
      default: "3.13"
  setupScript: |
    {{- .Files.Get "scripts/packages/python-uv.sh" | nindent 4 }}

