apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cps1-gateway-certificate
spec:
  secretName: cps1-gateway-certificate
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
  commonName: "*.app.cps1.tech"
  dnsNames:
    - "*.app.cps1.tech"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
