apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cps1-registry-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cps1-registry
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cps1-registry
  template:
    metadata:
      labels:
        app: cps1-registry
    spec:
      containers:
        - name: registry
          image: docker.io/registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          env:
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
      volumes:
        - name: registry-storage
          persistentVolumeClaim:
            claimName: cps1-registry-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cps1-registry
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: cps1-registry
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 30000
  type: NodePort
