apiVersion: v1
kind: Secret
metadata:
  name: gitlab-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  applicationId: {{ .Values.config.gitlab.applicationId }}
  groupId: "{{ .Values.config.gitlab.groupId }}"
  secret: {{ .Values.config.gitlab.secret }}
