---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: 3001
{{- if not .Values.config.tls.enabled }}
      nodePort: 30001
  type: NodePort
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway
  namespace: {{ .Release.Namespace }}
{{- if .Values.gateway.service.annotations }}
  annotations:
{{ toYaml .Values.gateway.service.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    app: {{ .Release.Name }}-gateway
  ports:
{{- if .Values.config.tls.enabled }}
    - name: ssh
      protocol: TCP
      port: {{ .Values.config.gateway.sshPort }}
      targetPort: 2222
    - name: https
      protocol: TCP
      port: {{ .Values.config.gateway.httpsPort }}
      targetPort: 8443
  type: LoadBalancer
{{- else }}
    - name: ssh
      protocol: TCP
      port: 2222
      nodePort: 30022
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080
  type: NodePort
{{- end }}
