{{ if .Values.config.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-gateway-certificate
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-gateway-certificate
  revisionHistoryLimit: 1
  privateKey:
    rotationPolicy: Always
  commonName: "*.{{- default .Values.config.hostname .Values.config.gateway.hostname }}"
  dnsNames:
    - "*.{{- default .Values.config.hostname .Values.config.gateway.hostname }}"
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: {{ required "A clusterIssuer is required when TLS is enabled. Make sure you set config.tls.clusterIssuer in values.yaml" .Values.config.tls.clusterIssuer }}
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.config.tls.clusterIssuer }}
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.config.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 3001
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.config.hostname }}
      secretName: {{ .Release.Name }}-ingress-certificate
{{ end }}
