{{- if has "go" .Values.includeTemplates }}
apiVersion: cps1.tech/v1alpha1
kind: Template
metadata:
  name: go-environment
spec:
  baseImage: ghcr.io/cps-1/base-image:20250624
  description: Includes latest Go.
  icon: /icons/go.svg
  template:
    components:
    - name: go_environment
      service:
        packages:
        - name: go
          properties:
            version: "1.24.4"
{{- end }}
