---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-x-builder
  namespace: cps1
data:
  builder.sh: |
    #!/bin/bash -x

    set -euxo pipefail
    ctrid=$(buildah from ghcr.io/cps-1/base-image:v21)

    buildah run $ctrid -- bash <<'EOF'
      #!/bin/bash

      set -euo pipefail

      # gerar logs bonitos
      # testar se estamos rodando como user

      HOME=/home/user
      : ${NODE_VERSION:="v22"}

      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash

      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

      nvm install ${NODE_VERSION}
      nvm alias default ${NODE_VERSION}

      chown -R user:user /home/user/.nvm

      node --help

    EOF

    buildah commit $ctrid kind-registry:5000/template-x
    buildah push --tls-verify=false kind-registry:5000/template-x
---
apiVersion: batch/v1
kind: Job
metadata:
  name: template-x-builder
  namespace: cps1
spec:
  template:
    spec:
      containers:
        - name: template-x-builder
          image: quay.io/buildah/stable
          command: [bash, /opt/cps1/builder.sh]
          volumeMounts:
            - name: build-script
              mountPath: /opt/cps1
          securityContext:
            privileged: true
      volumes:
        - name: build-script
          configMap:
            name: template-x-builder
      restartPolicy: Never
  backoffLimit: 3
