name: Release Charts
on:
  push:
    branches:
      - main
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest
      - name: Package Releases
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          mkdir -p .cr-release-packages
          for chart in charts/*; do
            if ! git diff --quiet HEAD~1 -- "$chart"; then
              CHART_NAME=$(basename "$chart")
              helm package "$chart" --destination .cr-release-packages --version "0.0.${DATE_TAG}-N"
            fi
          done
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_packaging: true
          skip_existing: true
          #packages_with_index: true
          #config: ./.github/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
