apiVersion: v1
kind: Namespace
metadata:
  name: devworkspace-controller
  labels:
    name: devworkspace-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-serviceaccount
  namespace: devworkspace-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-leader-election-role
  namespace: devworkspace-controller
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
  name: devworkspace-controller-edit-workspaces
rules:
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  - devworkspacetemplates
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings
  - devworkspaceoperatorconfigs
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-role
rules:
- apiGroups:
  - ""
  resourceNames:
  - workspace-preferences-configmap
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - workspace-credentials-secret
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resourceNames:
  - devworkspace-controller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  - extensions
  resources:
  - deployments
  - replicasets
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.openshift.io
  resourceNames:
  - cluster
  resources:
  - proxies
  verbs:
  - get
- apiGroups:
  - controller.devfile.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings
  verbs:
  - '*'
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
- apiGroups:
  - workspace.devfile.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: devworkspace-controller-view-workspaces
rules:
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  - devworkspacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controller.devfile.io
  resources:
  - devworkspaceroutings
  - devworkspaceoperatorconfigs
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-leader-election-rolebinding
  namespace: devworkspace-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devworkspace-controller-leader-election-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: devworkspace-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devworkspace-controller-proxy-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: devworkspace-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: devworkspace-controller-role
subjects:
- kind: ServiceAccount
  name: devworkspace-controller-serviceaccount
  namespace: devworkspace-controller
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-manager-service
  namespace: devworkspace-controller
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: conversion
  selector:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-metrics
  namespace: devworkspace-controller
spec:
  ports:
  - name: metrics
    port: 8443
    targetPort: metrics
  selector:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-manager
  namespace: devworkspace-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-controller
      app.kubernetes.io/part-of: devworkspace-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devworkspace-controller
        app.kubernetes.io/part-of: devworkspace-operator
    spec:
      containers:
      - args:
        - /usr/local/bin/devworkspace-controller
        - --enable-leader-election
        - --metrics-addr=127.0.0.1:8080
        env:
        - name: WEBHOOK_SECRET_NAME
          value: devworkspace-operator-webhook-cert
        - name: RELATED_IMAGE_devworkspace_webhook_server
          value: quay.io/devfile/devworkspace-controller:v0.29.0
        - name: RELATED_IMAGE_kube_rbac_proxy
          value: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        - name: RELATED_IMAGE_project_clone
          value: quay.io/devfile/project-clone:v0.29.0 
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: devworkspace-operator
        - name: CONTROLLER_SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: MAX_CONCURRENT_RECONCILES
          value: "5"
        - name: WEBHOOKS_SERVER_MEMORY_LIMIT
          value: 300Mi
        - name: WEBHOOKS_SERVER_MEMORY_REQUEST
          value: 20Mi
        - name: WEBHOOKS_SERVER_CPU_LIMIT
          value: 200m
        - name: WEBHOOKS_SERVER_CPU_REQUEST
          value: 100m
        - name: RELATED_IMAGE_pvc_cleanup_job
          value: registry.access.redhat.com/ubi8-micro:8.8-1
        - name: RELATED_IMAGE_async_storage_server
          value: quay.io/eclipse/che-workspace-data-sync-storage:0.0.1
        - name: RELATED_IMAGE_async_storage_sidecar
          value: quay.io/eclipse/che-sidecar-workspace-data-sync:0.0.1
        image: quay.io/devfile/devworkspace-controller:v0.29.0 
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: liveness-port
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: devworkspace-controller
        ports:
        - containerPort: 9443
          name: conversion
          protocol: TCP
        - containerPort: 6789
          name: liveness-port
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /readyz
            port: liveness-port
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: webhook-tls-certs
          readOnly: true
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: metrics
      serviceAccountName: devworkspace-controller-serviceaccount
      terminationGracePeriodSeconds: 10
      volumes:
      - name: webhook-tls-certs
        secret:
          defaultMode: 420
          secretName: devworkspace-operator-webhook-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-serving-cert
  namespace: devworkspace-controller
spec:
  dnsNames:
  - devworkspace-webhookserver.devworkspace-controller.svc
  - devworkspace-webhookserver.devworkspace-controller.svc.cluster.local
  - devworkspace-controller-manager-service.devworkspace-controller.svc
  - devworkspace-controller-manager-service.devworkspace-controller.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: devworkspace-controller-selfsigned-issuer
  secretName: devworkspace-operator-webhook-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: devworkspace-controller
    app.kubernetes.io/part-of: devworkspace-operator
  name: devworkspace-controller-selfsigned-issuer
  namespace: devworkspace-controller
spec:
  selfSigned: {}
