apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: {{ .Values.config.clusterIssuer }}
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.config.hostname }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 3001
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.config.hostname }}
      secretName: ingress-cps1app-tls
