---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cps1-role
rules:
  - apiGroups: [workspace.devfile.io]
    resources: [devworkspaces, devworkspacetemplates]
    verbs: [get, watch, list, create, patch, update, delete]
  - apiGroups: [""]
    resources: [configmaps, secrets, namespaces]
    verbs: [get, list, create, patch, update, delete]
  - apiGroups: ["networking.k8s.io"]
    resources: [ingresses]
    verbs: [get, watch, list, create, patch, update, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cps1-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cps1-role
  apiGroup: rbac.authorization.k8s.io
